stages:
  - test

cache:
  paths:
     - .gradle
     - $HOME/.gradle

test:
  stage: test
  image: openjdk:11
  artifacts:
    paths:
      - build/libs/alarm-service.jar
  before_script:
    - java --version
    - pwd
  script:
    - ./gradlew sonarqube -Dsonar.login=$SONARCLOUD_LOGIN -Dsonar.projectVersion=$CI_COMMIT_SHORT_SHA
