stages:
  - test

before_script:
  - export GRADLE_USER_HOME=/builds/gradle_home

cache:
  paths:
     - .gradle
     - /builds/gradle_home

test:
  stage: test
  image: openjdk:11
  artifacts:
    paths:
      - build/libs/alarm-service.jar
  before_script:
    - java --version
    - pwd
  script:
    - ./gradlew sonarqube -Dsonar.login=$SONARCLOUD_LOGIN -Dsonar.projectVersion=$CI_COMMIT_SHORT_SHA
  after_script:
    - ls -la /builds/gradle_home
