stages:
  - test

test:
  stage: test
  image: openjdk:11
  before_script:
    - java --version
    - pwd
  script:
    - ./gradlew sonarqube -Dsonar.login=$SONARCLOUD_LOGIN -Dsonar.projectVersion=$CI_COMMIT_SHORT_SHA
